export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM';
export const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM';
export const CLEAR_CONSTRUCTOR: 'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR';
export const DELETE_ITEM_BY_INDEX: 'DELETE_ITEM_BY_INDEX' = 'DELETE_ITEM_BY_INDEX';
export const CHANGE_ITEMS_ORDER: 'CHANGE_ITEMS_ORDER' = 'CHANGE_ITEMS_ORDER';