export const SHOW_INGREDIENT_DETAILS_POPUP: 'SHOW_INGREDIENT_DETAILS_POPUP' = 'SHOW_INGREDIENT_DETAILS_POPUP';
export const ADD_INGREDIENT_INFO_TO_MODAL: 'ADD_INGREDIENT_INFO_TO_MODAL' = 'ADD_INGREDIENT_INFO_TO_MODAL';
export const REMOVE_INGREDIENT_INFO_TO_MODAL: 'REMOVE_INGREDIENT_INFO_TO_MODAL' = 'REMOVE_INGREDIENT_INFO_TO_MODAL';
